# Generated by Django 5.0.14 on 2026-08-11 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0002_seed_services_and_industries'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('client_name', models.CharField(help_text="e.g. 'Demo Fashion Brand' — clearly marked as demo until real clients are added.", max_length=150)),
                ('category', models.CharField(choices=[('websites', 'Websites'), ('ecommerce', 'E-commerce'), ('branding', 'Branding'), ('social-media', 'Social Media'), ('seo', 'SEO'), ('ads', 'Ads'), ('creative', 'Creative')], db_index=True, max_length=20)),
                ('short_description', models.CharField(help_text='Shown on grid cards.', max_length=200)),
                ('challenge', models.TextField()),
                ('objective', models.TextField()),
                ('strategy', models.TextField()),
                ('solution', models.TextField(help_text='What was actually built/delivered.')),
                ('results', models.TextField()),
                ('technologies', models.JSONField(blank=True, default=list)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='portfolio/')),
                ('testimonial_quote', models.TextField(blank=True)),
                ('testimonial_author', models.CharField(blank=True, max_length=100)),
                ('testimonial_role', models.CharField(blank=True, max_length=150)),
                ('meta_title', models.CharField(blank=True, max_length=70)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_studies', to='services.industry')),
                ('services', models.ManyToManyField(blank=True, related_name='case_studies', to='services.service')),
            ],
            options={
                'verbose_name_plural': 'Case studies',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseStudyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('case_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='portfolio.casestudy')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='casestudy',
            index=models.Index(fields=['slug', 'is_published'], name='portfolio_c_slug_5e3255_idx'),
        ),
        migrations.AddIndex(
            model_name='casestudy',
            index=models.Index(fields=['category', 'is_published'], name='portfolio_c_categor_4e4b73_idx'),
        ),
        migrations.AddIndex(
            model_name='casestudy',
            index=models.Index(fields=['created_at'], name='portfolio_c_created_48da21_idx'),
        ),
    ]
