# Generated by Django 5.0.14 on 2026-08-13 05:22

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_casestudy_featured_image_webp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudy',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/', validators=[apps.core.validators.validate_image_file_size]),
        ),
        migrations.AlterField(
            model_name='casestudyimage',
            name='image',
            field=models.ImageField(upload_to='portfolio/gallery/', validators=[apps.core.validators.validate_image_file_size]),
        ),
    ]
