# Generated by Django 5.0.14 on 2026-08-13 05:22

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_seed_demo_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='team/', validators=[apps.core.validators.validate_image_file_size]),
        ),
    ]
