# Generated by Django 5.0.14 on 2026-08-10 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Luminous Ever', max_length=100)),
                ('tagline', models.CharField(blank=True, help_text='Short positioning line, e.g. shown near the logo or in meta tags.', max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('whatsapp_number', models.CharField(blank=True, help_text='Digits only, with country code, e.g. 91XXXXXXXXXX', max_length=20)),
                ('address', models.TextField(blank=True)),
                ('business_hours', models.CharField(blank=True, max_length=200)),
                ('instagram_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('default_meta_title', models.CharField(blank=True, max_length=70)),
                ('default_meta_description', models.CharField(blank=True, max_length=160)),
                ('default_og_image', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('google_analytics_id', models.CharField(blank=True, max_length=30)),
                ('google_search_console_verification', models.CharField(blank=True, max_length=100)),
                ('meta_pixel_id', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='e.g. Projects Delivered', max_length=100)),
                ('value', models.CharField(help_text='e.g. 50+, 95%, 3X', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
