# Generated by Django 5.0.14 on 2026-08-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed_demo_statistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='mission_statement',
            field=models.TextField(blank=True, help_text='Shown on the About page.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='vision_statement',
            field=models.TextField(blank=True, help_text='Shown on the About page.'),
        ),
    ]
