# Generated by Django 5.0.14 on 2026-08-13 05:22

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_update_site_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='default_og_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/', validators=[apps.core.validators.validate_image_file_size]),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='site/', validators=[apps.core.validators.validate_image_file_size]),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='site/', validators=[apps.core.validators.validate_image_file_size]),
        ),
    ]
