# Generated by Django 5.0.14 on 2026-08-11 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('tagline', models.CharField(help_text="e.g. 'Digital foundations'", max_length=120)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Service categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('short_description', models.CharField(help_text='Shown on service cards and index pages.', max_length=200)),
                ('hero_subtitle', models.TextField(help_text='1–2 sentence hero subheading for the detail page.')),
                ('problem', models.TextField(help_text='The problem this service solves.')),
                ('solution', models.TextField(help_text='How Luminous Ever solves it.')),
                ('features', models.JSONField(blank=True, default=list, help_text='List of {"title": "...", "description": "..."} objects.')),
                ('technologies', models.JSONField(blank=True, default=list, help_text='List of technology/tool names.')),
                ('benefits', models.JSONField(blank=True, default=list, help_text='List of benefit strings.')),
                ('who_its_for', models.JSONField(blank=True, default=list, help_text='List of audience descriptions.')),
                ('deliverables', models.JSONField(blank=True, default=list, help_text='List of deliverable strings.')),
                ('faqs', models.JSONField(blank=True, default=list, help_text='List of {"question": "...", "answer": "..."} objects.')),
                ('meta_title', models.CharField(blank=True, max_length=70)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='services.servicecategory')),
            ],
            options={
                'ordering': ['category__order', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('description', models.TextField(help_text='1–2 paragraph intro specific to this industry.')),
                ('challenges', models.JSONField(blank=True, default=list, help_text='List of industry-specific challenge strings.')),
                ('meta_title', models.CharField(blank=True, max_length=70)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relevant_services', models.ManyToManyField(blank=True, related_name='industries', to='services.service')),
            ],
            options={
                'verbose_name_plural': 'Industries',
                'ordering': ['order'],
                'indexes': [models.Index(fields=['slug', 'is_published'], name='services_in_slug_097ef4_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['slug', 'is_published'], name='services_se_slug_ee613e_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['category', 'is_published'], name='services_se_categor_7809a3_idx'),
        ),
    ]
