# Generated by Django 5.0.14 on 2026-08-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('company', models.CharField(blank=True, max_length=150)),
                ('designation', models.CharField(blank=True, max_length=150)),
                ('quote', models.TextField()),
                ('project_type', models.CharField(blank=True, help_text="e.g. 'Website & Branding'", max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('source', models.CharField(choices=[('direct', 'Direct / Manual'), ('google', 'Google Review')], default='direct', max_length=10)),
                ('google_review_url', models.URLField(blank=True, help_text='Reserved for future Google Review integration.')),
                ('rating', models.PositiveSmallIntegerField(default=5, help_text='1–5 stars')),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
