# Generated by Django 5.0.14 on 2026-08-11 11:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Blog categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('excerpt', models.CharField(max_length=300)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('content', models.TextField(help_text='HTML content (h2/h3/p tags). Rendered as-is — admin-trusted input only.')),
                ('reading_time', models.PositiveIntegerField(blank=True, help_text='Minutes. Auto-calculated on save if left blank.', null=True)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('meta_title', models.CharField(blank=True, max_length=70)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='blog/og/')),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='blog.blogcategory')),
            ],
            options={
                'ordering': ['-published_date'],
                'indexes': [models.Index(fields=['slug', 'is_published'], name='blog_blogpo_slug_c2a5f8_idx'), models.Index(fields=['category', 'is_published'], name='blog_blogpo_categor_66fea9_idx'), models.Index(fields=['published_date'], name='blog_blogpo_publish_a9bbd5_idx')],
            },
        ),
    ]
