# Generated by Django 5.0.14 on 2026-08-12 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_seed_blog_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='featured_image_webp',
            field=models.ImageField(blank=True, editable=False, help_text='Auto-generated from featured_image — do not upload directly.', null=True, upload_to='blog/webp/'),
        ),
    ]
