# Generated by Django 5.0.14 on 2026-08-13 05:22

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost_featured_image_webp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/', validators=[apps.core.validators.validate_image_file_size]),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='og_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/og/', validators=[apps.core.validators.validate_image_file_size]),
        ),
    ]
